### ISSUE TITLE
Great jod! I am very interested in how to make one cloth to fit various of bodies automatically.Can you give me some tips of the algorithm you use or any other relevant research I can find.Thanks very much.

### ISSUE THREAD

**Issue by YangChenHust** [shanemankiw/SO-SMPL#2]

**Comment by shanemankiw** [comment]
Sorry for the late reply, I am just seeing this. Thanks for your interests. 

It depends on the garment you are using. In our case, the extracted garment is a surface mesh, and can be put into Marvelous Designer for physical simulation. This includes garment draping (fit a clothes on different bodies).

If you are looking for a learning-based algorithm, there are a few garment draping projects. Maybe you can refer to something like this: https://github.com/liren2515/DrapeNet.

Hope that helps!

**Comment by YangChenHust** [comment]
> Sorry for the late reply, I am just seeing this. Thanks for your interests.
> 
> It depends on the garment you are using. In our case, the extracted garment is a surface mesh, and can be put into Marvelous Designer for physical simulation. This includes garment draping (fit a clothes on different bodies).
> 
> If you are looking for a learning-based algorithm, there are a few garment draping projects. Maybe you can refer to something like this: https://github.com/liren2515/DrapeNet.
> 
> Hope that helps!

Thanks for your answer.
