### ISSUE TITLE
Hi, I have a question!

### ISSUE THREAD

**Issue by jjr2930** [shanemankiw/SO-SMPL#3]
Your research is very interesting.

I have one question.

When you create a character using your method, is that character rigged?

Rigging refers to the act of planting bones in a 3D character.

**Comment by shanemankiw** [comment]
The character is not rigged directly, but we do have its  joints and the kinematic tree, since our method is based on SMPL-X. 
I guess there are some tools you can use to automatically rig the generated mesh? btw we will also provide code for driving the character with SMPL motion sequences.

**Comment by jjr2930** [comment]
thanks your answer, it is good answer to me
