### ISSUE TITLE
Question about ControlNet

### ISSUE THREAD

**Issue by sunshineatnoon** [shanemankiw/SO-SMPL#4]
Hi, authors,

I recently read your awesome work. I have one question about the ControlNet SDS, did you use an off-the-shelf ControlNet or fine-tune with your own dataset (if so, which dataset). Thanks and looking forward to your reply!

**Comment by shanemankiw** [comment]
Hi,

Thanks for your interests! We use an off-the-shelf ControlNet [here](https://huggingface.co/lllyasviel/control_v11p_sd15_openpose)

Happy Chinese New Year!

**Comment by sunshineatnoon** [comment]
Thanks so much! @shanemankiw 
Happy Chinese New Year to you too :)
