### ISSUE TITLE
Question about shading

### ISSUE THREAD

**Issue by sunshineatnoon** [shanemankiw/SO-SMPL#5]
Hi, I have a question about the implementation of eq. 7 in the paper (shading computation). How did you sample the ambient light intensity (la) and point light intensity (ld)? Thanks!

**Comment by shanemankiw** [comment]
> Hi, I have a question about the implementation of eq. 7 in the paper (shading computation). How did you sample the ambient light intensity (la) and point light intensity (ld)? Thanks!

Hi, we use a random sampling strategy proposed in [Magic3D](https://research.nvidia.com/labs/dir/magic3d/), which randomly samples the ambient intensity and diffuse intensity. You can refer to the code here:
https://github.com/threestudio-project/threestudio/blob/cd462fb0b73a89b6be17160f7802925fe6cf34cd/threestudio/models/materials/diffuse_with_point_light_material.py#L63

**Comment by sunshineatnoon** [comment]
Thanks so much!
