### ISSUE TITLE
SDS Loss Details

### ISSUE THREAD

**Issue by sunshineatnoon** [shanemankiw/SO-SMPL#6]
Hi, I'm trying to re-implement the OpenPose ControlNet supervision. Could you please provide more details? Is the implementation based on the [ControlNet guidance from threestudio](https://github.com/threestudio-project/threestudio/blob/cd462fb0b73a89b6be17160f7802925fe6cf34cd/threestudio/models/guidance/controlnet_guidance.py#L21) and what is the `guidance_scale`, `guidance_scale`? Thanks!

**Comment by shanemankiw** [comment]
> Hi, I'm trying to re-implement the OpenPose ControlNet supervision. Could you please provide more details? Is the implementation based on the [ControlNet guidance from threestudio](https://github.com/threestudio-project/threestudio/blob/cd462fb0b73a89b6be17160f7802925fe6cf34cd/threestudio/models/guidance/controlnet_guidance.py#L21) and what is the `guidance_scale`, `guidance_scale`? Thanks!

We did not use this exact code but the idea should be similar. ControlNet's guidance scale is set to 35.
