### ISSUE TITLE
FileNotFoundError when running stage1 script

### ISSUE THREAD

**Issue by CupidAIGC** [shanemankiw/SO-SMPL#7]
Hello,

I encountered an issue while running the following command:
bash scripts/stage1/public_loop_m.sh
The script throws the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'load/smplx/remesh/vest_cut_mask_2.npy'
It seems that the file vest_cut_mask_2.npy is missing from the specified directory. Could you please help me understand whether this file should be generated by a previous step, or if there is a missing file that needs to be included in the repository?
Thank you for your assistance!

**Comment by zhong2001** [comment]
Hello, I have also encountered this problem. Have you solved it?

**Comment by shanemankiw** [comment]
Hi, sorry for the late reply, I just got the notice today. I just uploaded the file to the onedrive link:

https://tamucs-my.sharepoint.com/:f:/g/personal/jionghao_tamu_edu/Ekeg21l-YJlIgHWBz5IDHW4BUHhuW2Iew8IbgRT43uh-MA?e=hcjQF6


Please let me know if you have more questions.

**Comment by zhong2001** [comment]
> Hi, sorry for the late reply, I just got the notice today. I just uploaded the file to the onedrive link:
> 
> https://tamucs-my.sharepoint.com/:f:/g/personal/jionghao_tamu_edu/Ekeg21l-YJlIgHWBz5IDHW4BUHhuW2Iew8IbgRT43uh-MA?e=hcjQF6
> 
> Please let me know if you have more questions.

Hello, it seems that I am still missing the vest_cut_mask_6.npy file when running the code. Do you have any similar files?
FileNotFoundError: [Errno 2] No such file or directory: 'load/smplx/remesh/vest_cut_mask_6.npy'

**Comment by shanemankiw** [comment]
Hi, I have updated the files and now they are all there. Thanks for the reminder!
